<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$erVal = error_reporting();
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.tablesorter.min.js?' . time());
$this->headScript()->appendFile($this->apiWebroot.'/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/jquery.dataTables.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/qibench.seedpoints.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/seedpoints/demo_table.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.tablesorter.css?<?php echo time()?>" />

<div class="viewMain">



<table id="seedpoints_table" class="display">
<thead>


<?php
echo '<tr class="header_row">';



foreach($this->tableHeaders as $dbCol => $tableHeader)
  {
  //if(array_search($dbCol,$excludedCols)) continue;
  echo '<th>'.$tableHeader.'</th>';
  }
?>
</tr>
</thead>
<tbody>
<?php
foreach($this->tableData as $row)
  {
  echo '<tr>';
//  $seedpointDao = $seedpoint['NistqiLesionSeedpoint'];
  foreach($row as $col)
    {
    //if(array_search($dbCol,$excludedCols)) continue;
    echo '<td><div>'.$col.'</div></td>';
    }
  
  echo "</tr>";
  }
?>

</tbody>
</table>

     <?php
      echo "
      <form class='genericForm' id='seedpointsForm' method='{$this->seedpointsForm['method']}'  action='{$this->seedpointsForm['action']}'>
          <div>
            {$this->seedpointsForm['submitExecute']}
          </div>
       </form>";
            //<span>{$this->seedpointsForm['submitLoad']}{$this->seedpointsForm['seepointsFileItemId']}</span>
       ?>

    
    
    <table id="topdebug">
<?php
foreach($this->topDebug as $prop => $value)
  {
  echo '<tr><td>'.$prop.'</td><td>'.$value.'</td></tr>';
  }
?>
        
    </table>    
    
    
    
    
    
    
    
    
    
<table id="debugRowsTable" class="tablesorter">
  <thead>
    <tr>
<?php
foreach($this->debugTableHeaders as $dbCol => $tableHeader)
  {
  echo '<th>'.$tableHeader.'</th>';
  }
?>
    </tr>
  </thead>
  <tbody>

<?php
foreach($this->debugTableData as $row)
  {
  echo '<tr>';
  foreach($row as $col)
    {
    echo '<td><div>'.$col.'</div></td>';
    }
  echo "</tr>";
  }
?>
  </tbody>
</table>
    
    
    
</div>
